name: ${name}
version: ${version}
main: com.aquiles.simpleportals.SimplePortalsPlugin
api-version: "1.19"
authors: [Aquiles]
description: Simple and performant shaped portals for Paper 1.19.4+
folia-supported: true
